### ISSUE TITLE
This tool is not working because of Free API death

### ISSUE THREAD

**Issue by eggplants** [uinput/deeplator#12]
Free API is dead: <https://www.deepl.com/jsonrpc>

https://github.com/uinput/deeplator/blob/6972ad587811569d0edecdea21f7235086b19f68/deeplator/translator.py#L5

**Comment by xavierbaez** [comment]
True

**Comment by eggplants** [comment]
See: https://github.com/Animenosekai/translate/blob/main/translatepy/translators/deepl.py
This project uses new JSON RPC endpoint: <https://www.deepl.com/PHP/backend/clientState.php?request_type=jsonrpc&il=EN>
