### ISSUE TITLE
PyPi package does not import after installing

### ISSUE THREAD

**Issue by shpigunov** [uinput/deeplator#3]
Hi, I'm trying to install and run Deeplator via pip, and I get:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/deeplator.py", line 7, in <module>
    from deeplator import Translator, VALID_LANGS
ImportError: cannot import name 'Translator'`

Upon examining the PyPi package here: 
https://pypi.python.org/pypi/deeplator/0.0.3

I found that the /deeplator/ directory is missing, so the module doesn't import properly. 
Would it be possible to re-upload the PyPi package with all the required files?

**Comment by uinput** [comment]
Fixed by 419bb8f43013c249a0afb6d4f1b0ebed7e7b9772. Thank you for reporting this issue!
